[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/knq/jwt"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/matoous/go-nanoid"

[[constraint]]
  branch = "master"
  name = "github.com/matryer/way"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[prune]
  go-tests = true
  unused-packages = true

[metadata.heroku]
  root-package = "github.com/nicolasparada/go-messenger-demo"
  go-version = "go1.10.3"
